# Generated by Django 2.2.6 on 2021-05-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='Значение по-умолчанию', help_text='Дайте короткое название задаче', max_length=100, verbose_name='Заголовок'),
        ),
    ]
